// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package postgres

import (
	"github.com/google/uuid"
)

type Product struct {
	ID            int32  `json:"id"`
	Name          string `json:"name"`
	Price         string `json:"price"`
	Description   string `json:"description"`
	StockQuantity int32  `json:"stock_quantity"`
}

type User struct {
	Fullname string    `json:"fullname"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	ID       uuid.UUID `json:"id"`
}
